<?php

/**
 * @file
 * Limits keyword indexing of only selected content types.
 */


/**
 * Implements hook_form_alter().
 */
function search_index_options_form_alter(&$form, &$form_state, $form_id) {
  // Get content types included for indexing.
  $search_index_options_content_types = config_get('search_index_options.settings', 'content_type_options');
  #sdpm($search_index_options_content_types);
  $search_index_options_nodes = config_get('search_index_options.settings', 'node_option');

  if ($form_id == 'search_admin_settings') {
    // Make the default search module impossible to turn off and save users
    // from the core search module's complaining message.
    $form['active']['search_active_modules']['#pre_render'][] = 'search_index_options_disable_element';
    $form['active']['search_active_modules']['#value_callback'] = 'search_index_options_form_type_checkboxes_value';
    // Make only active search modules available for setting as the default one.
    foreach ($form['active']['search_active_modules']['#default_value'] as $module_name) {
      if ($module_name != '0') {
        $active[$module_name] = $form['active']['search_active_modules']['#options'][$module_name];
      }
    }
    $form['active']['search_default_module']['#options'] = $active;

    // Could pull from $search_index_options_content_types if already saved, however new
    // content types can be created any moment, so we build it every time.
    $node_type_get_types = node_type_get_types();
    foreach ($node_type_get_types as $type => $content_type) {
      if (isset($search_index_options_content_types[$type])) {
        $default_value = $search_index_options_content_types[$type];
      }
      else {
        $default_value = '0';
      }
      $types[$type] = array(
        '#type' => 'checkbox',
        '#title' => check_plain($content_type->name),
        '#default_value' => $default_value,
      );
    }
    $content_type_options = array(
      '#tree' => TRUE,
      '#type' => 'fieldset',
      '#title' => 'Content type level indexing options',
      '#description' => t("Only nodes of the selected content types are included to the website's search index. If none selected then all nodes are indexed."),
      'search_index_options' => $types,
    );
    $form['content_type_options'] = $content_type_options;
    $node_index = array(
      '#type' => 'checkbox',
      '#title' => 'Enable node level indexing option?',
      '#default_value' => $search_index_options_nodes,
    );
    $node_option = array(
      '#tree' => TRUE,
      '#type' => 'fieldset',
      '#title' => 'Node level indexing option',
      '#description' => t("Enabling this will introduce a new option on node form's vertical menu to include or exclude content to/from search index."),
      'search_index_options' => $node_index,
    );
    $form['node_option'] = $node_option;
    $form['#submit'][] = 'search_index_options_settings';

    // Collect indexing stats per included content type.
    $report = '';
    if (!empty($search_index_options_content_types)) {
      $selected = FALSE;
      foreach ($search_index_options_content_types as $type => $included) {
        if ($included == TRUE) {
          $total = db_query('SELECT COUNT(*) FROM {node} WHERE type = :type', array(':type' => $type))->fetchField();
          $remaining = db_query("SELECT COUNT(*) FROM {node} n LEFT JOIN {search_dataset} d ON d.type = 'node' AND d.sid = n.nid WHERE (d.sid IS NULL OR d.reindex <> 0) AND n.type = :type", array(':type' => $type))->fetchField();
          if ($remaining != '0') {
            $count = format_plural($remaining, '<strong><em>1</em></strong> node left to index or is excluded from indexing.', '<strong><em>@count</em></strong> nodes left to index or are excluded from indexing.');
          }
          else {
            $count = '';
          }
          $percentage = ((int) min(100, 100 * ($total - $remaining) / max(1, $total))) . '%';
          // Finally output all the stats.
          $report .= '<p>' . t(
            '<strong>%percentage</strong> of <strong>%total</strong>  <em>@content-type</em> nodes have been indexed.',
            array(
            '%percentage' => $percentage,
            '%total' => $total,
            '@content-type' => $node_type_get_types[$type]->name,
          )
          )
          . ' ' . $count . '</p>';
          $selected = TRUE;
        }
      }
      if ($selected == TRUE) {
        // Collect total indexing stats.
        $remaining = 0;
        $total = 0;
        foreach (config_get('search.settings', 'search_active_modules') as $module) {
          if ($status = module_invoke($module, 'search_status')) {
            $remaining += $status['remaining'];
            $total += $status['total'];
          }
        }
        $remaining_count = format_plural($remaining, '<strong>1</strong> node left to index or excluded from indexing.', '<strong>@count</strong> nodes left to index or excluded from indexing.');
        $percentage = ((int) min(100, 100 * ($total - $remaining) / max(1, $total))) . '%';
        $report .= '<p>' . t('<strong>%percentage</strong> of total <strong>%total</strong> nodes have been indexed.', array('%percentage' => $percentage, '%total' => $total)) . ' ' . $remaining_count . '</p>';
        $form['indexing']['status'] = array('#markup' => $report);
      }
    }
  }


  // Introduce UI option to exclude individual nodes ...
  if ($search_index_options_nodes == TRUE) {
    if (strpos($form_id, '_node_form') !== FALSE) {
      // Create a new fieldset for node's vertical tab.
      $form['search_index_options'] = array(
        '#type' => 'fieldset',
        '#title' => t('Search index option'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        '#tree' => TRUE,
        '#weight' => -99,
        '#group' => 'additional_settings',
        '#attached' => array(
          'js' => array(
            'vertical-tabs' => backdrop_get_path('module', 'search_index_options') . '/js/search_index.js',
          ),
        ),
      );

      $exist = db_query('SELECT nid FROM {search_index_options} WHERE nid = :nid', array(':nid' => $form['nid']['#value']))->fetchField();
      if (isset($search_index_options_content_types[$form['#bundle']]) && $search_index_options_content_types[$form['#bundle']] == FALSE) {
        if (empty($exist)) {
          $default_value = FALSE;
        }
        else {
          $default_value = TRUE;
        }
      }
      else {
        if (empty($exist)) {
          $default_value = TRUE;
        }
        else {
          $default_value = FALSE;
        }
      }

      $form['search_index_options']['option'] = array(
        '#type' => 'checkbox',
        '#title' => t('Searchable'),
        '#default_value' => $default_value,
      );
      // Additional submit handler.
      $form['actions']['submit']['#submit'][] = 'search_index_options_submit';
    }
  }
}

/**
 * Submit handler.
 */
function search_index_options_submit(&$form, &$form_state) {

  $search_index_options_content_types = config_get('search_index_options.settings','content_type_options');

  if (!isset($search_index_options_content_types)) {
    // No content type set, so all nodes are searchable.
    $normal_order = TRUE;
  }
  else {
    if ($search_index_options_content_types[$form['#bundle']] == TRUE) {
      $normal_order = TRUE;
    }
    else {
      $normal_order = FALSE;
    }
  }

  if ($normal_order == TRUE) {
    if ($form_state['input']['search_index_options']['option'] == FALSE) {
      db_merge('search_index_options')
      ->key(array('nid' => $form['#node']->nid))
      ->fields(array(
        'nid' => $form['#node']->nid,
        'type' => $form['#node']->type,
        'title' => $form['#node']->title,
      ))
      ->execute();
    }
    else {
      // Exclude non-searchable content type node.
      $num_deleted = db_delete('search_index_options')
        ->condition('nid', $form['#node']->nid)
        ->execute();
    }
  }
  else {
    if ($form_state['input']['search_index_options']['option'] == FALSE) {
      // Exclude non-searchable content type node.
      $num_deleted = db_delete('search_index_options')
        ->condition('nid', $form['#node']->nid)
        ->execute();
    }
    else {
      db_merge('search_index_options')
      ->key(array('nid' => $form['#node']->nid))
      ->fields(array(
        'nid' => $form['#node']->nid,
        'type' => $form['#node']->type,
        'title' => $form['#node']->title,
      ))
      ->execute();
    }
  }
}

/**
 * Submit handler for search_index_options_form_alter().
 */
function search_index_options_settings(&$form, &$form_state) {
  if (in_array(TRUE, $form_state['values']['content_type_options']['search_index_options'])) {
    config_set('search_index_options.settings', 'content_type_options', $form_state['values']['content_type_options']['search_index_options']);
  }
  else {
    config_clear('search_index_options.settings', 'content_type_options');
  }
  if ($form_state['values']['node_option']['search_index_options'] == FALSE) {
    config_clear('search_index_options.settings', 'node_option');
  }
  else {
    config_set('search_index_options.settings', 'node_option', TRUE);
  }
}

/**
 * Handler for disabling checkbox for the default search module.
 */
function search_index_options_disable_element($element) {
  $search_default_module = config_get('search.settings', 'search_default_module');
  foreach (element_children($element) as $key) {
    if ($key == $search_default_module) {
      $element[$key]['#attributes']['disabled'] = TRUE;
    }
  }
  return $element;
}

/**
 * Handler for returning value for disabled checkbox.
 */
function search_index_options_form_type_checkboxes_value($element, $input = FALSE) {
  if ($input !== FALSE) {
    $search_default_module = config_get('search.settings', 'search_default_module');
    $input[$search_default_module] = $search_default_module;
  }
  return form_type_checkboxes_value($element, $input);
}

/**
 * Implements hook_module_implements_alter().
 */
function search_index_options_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'cron') {
    unset($implementations['search']);
  }
}

/**
 * Implements hook_cron().
 */
function search_index_options_cron() {
  global $user;
  $original_user = $user;
  $old_state = backdrop_save_session();
  backdrop_save_session(FALSE);
  $user = user_load(1);

  // Register a shutdown function to ensure search_total is always up to date.
  backdrop_register_shutdown_function('search_update_totals');

  foreach (config_get('search.settings', 'search_active_modules') as $module) {
    $module == 'node' ? module_invoke('search_index_options', 'update_index') : module_invoke($module, 'update_index');
  }
  $user = $original_user;
  backdrop_save_session($old_state);
}

/**
 * Implements hook_update_index().
 */
function search_index_options_update_index() {
  $limit = (int) config_get('search.settings', 'search_cron_limit');
  // Get content types included for indexing.
  $search_index_options_content_types = config_get('search_index_options.settings', 'content_type_options');
  if (!empty($search_index_options_content_types)) {
    $selected = FALSE;
    foreach ($search_index_options_content_types as $type => $included) {
      if ($included == TRUE) {
        // Collect only selected types.
        $types[] = $type;
        $selected = TRUE;
      }
      // Collect content types just in case if none was selected.
      $all_types[] = $type;
    }
    if ($selected == FALSE) {
      // If none was selected then process all content types.
      $types = $all_types;
    }
  }
  else {
    // No content type is set on admin/config/search/settings, so let's iterate
    // and include all content types.
    $node_type_get_types = node_type_get_types();
    foreach ($node_type_get_types as $type => $included) {
      $types[] = $type;
    }
  }
  $search_index_options_nodes = config_get('search_index_options.settings', 'node_option');

  // Prepare all selected content type nodes.
  $result = db_query_range("SELECT n.nid FROM {node} n LEFT JOIN {search_dataset} d ON d.type = 'node' AND d.sid = n.nid WHERE (d.sid IS NULL OR d.reindex <> 0) AND n.type IN (:types) ORDER BY d.reindex ASC, n.nid ASC", 0, $limit, array(':types' => $types), array('target' => 'slave'));

  // Process nodes of only selected content types.
  foreach ($result as $node) {
    $node = node_load($node->nid);
    $opted = db_query('SELECT nid FROM {search_index_options} WHERE nid = :nid', array(':nid' => $node->nid))->fetchField();
    if ((!isset($search_index_options_content_types) && !isset($search_index_options_nodes)) || (isset($search_index_options_content_types) && !isset($search_index_options_nodes))) {
      // None of content types or node level index enabled yet, or
      // some content type included with node level off, so all must go in.
      _node_index_node($node);
    }
    elseif (!isset($search_index_options_content_types) && isset($search_index_options_nodes)) {
      // No content types, but node level index enabled.
      // Exclude opted out nodes.
      if (empty($opted)) {
        _node_index_node($node);
      }
    }
    elseif (isset($search_index_options_content_types) && isset($search_index_options_nodes)) {
      // Exclude opted out nodes.
      if ($node->nid != $opted) {
        _node_index_node($node);
      }
    }
  }

  // Process nodes of not-selected content types.
  if (isset($search_index_options_content_types) && isset($search_index_options_nodes)) {
    // Include opted in nodes of not-selected content types.
    foreach ($search_index_options_content_types as $type => $selected) {
      if ($selected == FALSE) {
        $opted = db_query('SELECT nid FROM {search_index_options} WHERE type = :type', array(':type' => $type))->fetchCol();
        if (!empty($opted)) {
          foreach ($opted as $key => $nid) {
            $node = node_load($nid);
            _node_index_node($node);
          }
        }
      }
    }
  }
}
